### ISSUE TITLE
Add jgmenu_toggle option

### ISSUE THREAD

**Issue by godalming123** [johanmalm/jgmenu#165]
I would like to be able run
```
jgmenu_toggle
```
To toggle my menu

**Comment by johanmalm** [comment]
When would you ever use this in practice?

jgmenu grabs both the keyboard and pointer, so you couldn't use user input to trigger close/hide the menu using a `jgmenu_toggle`

**Comment by godalming123** [comment]
Well then maybe you should be able to specify a jgmenu close key instead of just escape as it is quite hard to reach on the keyboard

**Comment by johanmalm** [comment]
We currently don't support user-defined keybinds. Maybe one for the future, but I think it would be better to do that properly rather than defining it for one particular actions (exit/close in this case).

The menu understands `^quit()`, so maybe that's an option?

I'll close this one for now, but do say if we ought consider this further.
