### ISSUE TITLE
Acknowledge workarea in menu positioning.

### ISSUE THREAD

**Issue by Vladimir-csp** [johanmalm/jgmenu#21]
Count menu_margin_{x,y} relative to workarea instead of whole screen when `at_pointer = 0`, acknowledge workarea geometry when `at_pointer = 1`.

This can provide more 'fire-and-forget' menu usage as it won't overlap with panels. For example, launching jgmenu from tint2 button with at_pointer=1 but within workarea should look good even without parsing tint2 positional options.

**Comment by johanmalm** [comment]
Note to self: consider adding to geo_get_max_itemarea_that_fits() when at_pointer=1

**Comment by johanmalm** [comment]
I'm just trying to think this through before coding. I'd really appreciate your thoughts.

I'm just considering the case where at_pointer == 0 for the minute.

If WM is not EWMH compliant, _NET_WORKAREA might not be populated (I'm assuming this; I've not checked). We want to survive this.

As we get nearer to v1.0, I feel an increased responsibility not to break backward compatibility. The recent syntax changes in 0.7.6 generated issues and angst. So if possible, avoid breakage.

Proposal:

We change menu_margin_{x,y} default values to -1.
If menu_margin_{x,y} == -1, we try to calculate panel/dock dimentions based on _NET_WORKAREA

This way we don't break backward compatibility. Anyone who already has menu_margin_{x,y} set in jgmenurc will not notice a difference (i.e. margin_{x,y} remains relative to screen rather than workarea)

It gets a bit deeper though. I think we'd have to make the following additional change wrt menu positioning:

Currently, (x,y) are set in the following order (i.e. bottom of list has higher precedence)

 - built-in defaults (config.c)
 - tint2rc
 - jgmenurc
 - tint2 env vars

(side-note: tint2 env vars are only set if using panel button/launcher/execp - i.e. if using keyboard shortcut, we can't read these.)

If tint2 env vars are set, the users cannot alter menu_margin_{x,y} (unless they set tint2_look=0). I hadn't really thought about this, but I think it would make sense for jgmenurc to have highest priority all the time.

So, the new proposed order would be:

 - built-in defaults (config.c)
 - tint2rc
 - tint2 env vars
 - _NET_WORKAREA (some function thereof)
 - jgmenurc (if menu_margin{x,y} >= 0)

**Comment by Vladimir-csp** [comment]
jgmenurc at the hightest priority is good.
On the other hand, an option like `geometry_fallback` similar to existing `*_fallback` parameters might be useful to some.
Alsot jgmenu is flexible enough already to do some magic on the user's side by making a separate optimized config for launching it from tint2.

As for the workarea, IMHO, a simpler way is to add `confine_to_workarea` option, default false. This will give backwards compatibility. If set to true and WM provides _NET_WORKAREA, swap screen space with workarea space for existing position calculation. If set to false, or WM does not provide workarea, use the whole screen as usual.

**Comment by johanmalm** [comment]
I think this works fine now. I'll close it issue, but do shout if there is a problem.

In slow time, I will refactor config.c to enable more sane config options wrt priority of menu_margin_{x,y}, _NET_WORKAREA and tint2 environment variables.

**Comment by Vladimir-csp** [comment]
I've found two issues with the current code:
1. jgmenu seems to ignore confine_to_workarea value and always behave as `1`
2. I am launching jgmenu by right-clicking on tint2 empty space (pass-through to root window, where openbox launches jgmenu command). On mouse release menu closes.

**Comment by johanmalm** [comment]
1. I removed "config_to_workarea". I've got a better plan for config options. I think it's okay to leave it enabled for a little whilte until I get this sorted out.
2. Very goot spot!!!
I had tried with the following in ~/.config/openbox/rc.xml
`<mousebind button="Right" action="Release">
  <action name="Execute">
    <command>jgmenu_run</command>
  </action>
</mousebind>`
However, with "Press" instead of "Release" it didn't play well. I guess that's what you had.
Commit 8327c97 solves it.

**Comment by Vladimir-csp** [comment]
Premature closing is fixed.
I have this action bound to "press" for some reason, but it executes on release anyway.

**Comment by johanmalm** [comment]
Thanks

**Comment by johanmalm** [comment]
Hi Vladimir - hope all is well with you.

I'm having a slight problem with issue #56 - I think it originates from commit 0c4f42

I think _NET_WORKAREA works well in the "at_pointer=0" mode when using panels other that tint2. 

However, for at_pointer=1, there are some short-comings which would take significant re-writing or (possibly and) make the code quite complicated.

There are at least couple of options:

(a) revert that commit and thereby use the whole monitor for at_pointer=1

(b) implent your "confine_to_workarea" suggestion. I haven't given this a great deal of thought, but think it would take me a while. The current code base just isn't aligned to it, and I think we'd see lots of conditionals and mess. We'd have to track the workareas for each monitor, consider clicks outside these areas, etc.

As you can probably tell, I favour (a) in the interest of keeping the code clean and not having to re-write too much. However, you have given this project so much thought and I value your input, so I don't want to just drop functionality without consulting you.

**Comment by Vladimir-csp** [comment]
Hi. I do not have access to a multi-monitor setup this week. What does `wmctrl -d` show in that complex situation?  I mean, if it correctly shows workareas, it might have a solution in the code.

I'm not opposed to reverting workarea stuff. It's just a matter of balance between code cleanness and UI cleanness, do what you think is necessary.
