### ISSUE TITLE
Fixed size scrollable submenus?

### ISSUE THREAD

**Issue by varmanishant** [johanmalm/jgmenu#58]
Right now the submenus come according to the parent menu's position. The lower the item is, the submenu also drifts downwards.

Is it possible to make it fixed in size and position with respect to the bottom? A simple scroll arrow to allow for infinite scroll would be nice. I think most of the standard menu's are like this.

Anyway, thanks for this program.

**Comment by johanmalm** [comment]
Thanks for the ideas. Let's take one at a time:

(a) Regarding the submenu position, I'm unsure exactly what you mean. Could you help tease out the details.

I'm happy to implement something like this as long as it doesn't make the code base too messy.

- When you say fixed in size - do you mean height only?
- When you say with respect to the bottom - do you refer to a menu where "menu_valign = bottom"?

(b) Regarding the "scroll arrow", it's on my TODO list. It's just not got near the top yet.

**Comment by varmanishant** [comment]
Thanks for the reply @johanmalm . Here are [two](https://imgur.com/a/l9tEryv) images explaining both scenarios.

**Comment by johanmalm** [comment]
Okay, I get it.
I am gradually developing jgmenu to be able to be able to look like either of your two examples.
I had envisaged doing it with widgets + ^root() (which will set the root menu to a specific tag).
I like your idea though and will implement that too.
We may need the following config options. 
- sub_valign
- sub_height
- sub_margin_y
I'll give it some thought before embarking on code.

**Comment by johanmalm** [comment]
I think this has been implemented now (albeit differently to how originally envisaged) using widgets.
See theme greeneye.
I’ll close on the assumption that this is satisfactory.

**Comment by varmanishant** [comment]
Thank You, I will check it out!
