### ISSUE TITLE
Increase version number from 1.5 to 1.51

### ISSUE THREAD

**Issue by semeion** [johanmalm/jgmenu#72]
The bellow bugfix will be never updated in Arch linux repository if you don´t increase version number, for example, from 1.5 to 1.51.  

https://github.com/johanmalm/jgmenu/issues/69

**Comment by RobertZenz** [comment]
Correct me if I'm wrong, but shouldn't the maintainer of the Arch package be capable of releasing a custom version with this patch?

**Comment by johanmalm** [comment]
I have previously done a PATCH release for these types of bugs. I'm sorry I was a bit slow of the mark with this one. I hesitated because I wanted to run some unit tests and do some further proving.

I order to close this out, I will do MINOR release today and sweep it up that way. There are enough other fixes to warrant a release anyway :smile: 

@RobertZenz Yes

**Comment by johanmalm** [comment]
Done. v1.6 has been released. Arch Linux jgmenu package has been flagged out-of-date.
